# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main", "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.19.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}
      - name: Get Commit Message
        run: |
          GITHUB_COMMIT_URL="https://github.com/${{ github.repository }}/commit/"
          WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}
          REPO_NAME=${{ github.event.repository.name }}
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          NUMBER=$(git rev-list ${{github.event.before}}...${{github.event.after}} --count)
          SLACK_TEXT="$(git log -n ${NUMBER} --pretty=format:"%h" > logs.txt)"
          SLACK_TEXTS=""
          SHA_IDS=""
          for (( i=1; i<="${NUMBER}"; i++ ))
          do
            commit=$(grep -n ${i} logs.txt | sed -e "s@${i}:@@g")
            element="$(git show ${commit} --pretty=format:"%h" --no-patch)"
            SLACK_TEXT="$(git show ${element} --pretty=format:"%h%x09%an%x09%s")"
            echo "${SLACK_TEXT}"
            REPLACE_TEXT="\n><${GITHUB_COMMIT_URL}${element}|${element}>"
            SLACK_TEXT=$(echo $SLACK_TEXT | sed -e "s@$element@$REPLACE_TEXT@g")
            SLACK_TEXTS="${SLACK_TEXTS}${SLACK_TEXT}"
          done
          echo "${SLACK_TEXTS}"
          SLACK_HEADER="*${REPO_NAME} ${GIT_BRANCH}*"
          REPLACEMENT_WITH_MESSAGE="${SLACK_HEADER}${SLACK_TEXTS}"
          MESSAGES=$(echo '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"'"${REPLACEMENT_WITH_MESSAGE}"'"}}]}')
          echo "${MESSAGES}"
          curl -X POST -H 'Content-type: application/json' --data "${MESSAGES}" ${WEBHOOK_URL}
        continue-on-error: true