# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main", "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.19.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}
      - name: Get Commit Message
        run: |
          WEBHOOK_URL='https://hooks.slack.com/services/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'
          REPO_NAME=${{ github.event.repository.name }}
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          NUMBER=$(git rev-list ${{github.event.before}}...${{github.event.after}} --count)
          SLACK_TEXT="${REPO_NAME} ${GIT_BRANCH}\n $(git log -n ${NUMBER} --pretty=format:"%h%x09%an%x09%s")"
          echo "${SLACK_TEXT}"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"${SLACK_TEXT}"}' ${WEBHOOK_URL}
        continue-on-error: true